"""
Django settings for mylinen project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key


def env(name, default=None, required=False):
    value = os.environ.get(name, default)
    if required and not value:
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return value


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
if not SECRET_KEY:
    SECRET_KEY = get_random_secret_key()
    if not DEBUG:
        warnings.warn(
            "SECRET_KEY is not set. A temporary key was generated; set SECRET_KEY "
            "in production so sessions and password reset tokens remain stable.",
            RuntimeWarning,
        )

ALLOWED_HOSTS = ['127.0.0.1',
    'localhost',
    'mylinen.onrender.com',
    '.onrender.com']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "anymail",
    "accounts",
    "products",
    "cart",
    "orders.apps.OrdersConfig",
    "payments",
    "shipping",
    'wishlist',
    'notifications.apps.NotificationsConfig',
    # Social Auth
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    
    'cloudinary',
    'cloudinary_storage',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID', ''),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET', ''),
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Allauth Settings
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "mylinen.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart_contents",
            ],
        },
    },
]

WSGI_APPLICATION = "mylinen.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
import os

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    
    
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_STORAGE = {}
if all(env(name) for name in ("CLOUDINARY_CLOUD_NAME", "CLOUDINARY_API_KEY", "CLOUDINARY_API_SECRET")):
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': env("CLOUDINARY_CLOUD_NAME"),
        'API_KEY': env("CLOUDINARY_API_KEY"),
        'API_SECRET': env("CLOUDINARY_API_SECRET"),
    }
elif not DEBUG and not env("CLOUDINARY_URL"):
    warnings.warn(
        "Cloudinary credentials must be set with CLOUDINARY_URL or "
        "CLOUDINARY_CLOUD_NAME/CLOUDINARY_API_KEY/CLOUDINARY_API_SECRET for persistent media storage.",
        RuntimeWarning,
    )
import os

if os.environ.get("CLOUDINARY_URL"):
   STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

AUTH_USER_MODEL = "accounts.User"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

RAZORPAY_KEY_ID = env("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = env("RAZORPAY_KEY_SECRET", "")
# Email Configuration

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = int(env('EMAIL_PORT', 587))
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_TIMEOUT = int(env('EMAIL_TIMEOUT', 20))

EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_SEND_ASYNC = env_bool('EMAIL_SEND_ASYNC', False)

# Resend (HTTPS API) — works on Render free tier where outbound SMTP ports are blocked.
# https://anymail.dev/en/stable/esps/resend/
RESEND_API_KEY = env('RESEND_API_KEY', '').strip()
ANYMAIL = {}
if RESEND_API_KEY:
    ANYMAIL = {'RESEND_API_KEY': RESEND_API_KEY}

configured_email_backend = env('EMAIL_BACKEND')
if configured_email_backend:
    EMAIL_BACKEND = configured_email_backend
elif RESEND_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
elif DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
    warnings.warn(
        "No transactional email configured: set RESEND_API_KEY (recommended on Render free) "
        "or EMAIL_HOST_USER and EMAIL_HOST_PASSWORD for SMTP.",
        RuntimeWarning,
    )

DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL') or (
    f'MyLinen <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'MyLinen <onboarding@resend.dev>'
)
SERVER_EMAIL = env('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

SITE_URL = env('SITE_URL', 'https://mylinen.onrender.com')
LOGIN_OTP_SENDER = env('LOGIN_OTP_SENDER', '')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
