# Generated by Django 6.0 on 2026-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_product_remove_orderitem_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangerequest',
            name='is_refunded',
            field=models.BooleanField(default=False, help_text='Checked if the refund has been credited to wallet'),
        ),
    ]
