# Generated by Django 6.0 on 2026-05-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_returnexchangerequest_is_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
