# Generated by Django 6.0 on 2026-05-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Use Variant MRP. Maximum Retail Price (Strikethrough price)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='[DEPRECATED] Use Variant Price. Selling Price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deprecated_images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productsizestock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deprecated_size_stocks', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Override MRP for this color', max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Override Price for this color', max_digits=10, null=True)),
                ('image', models.ImageField(help_text='Primary image for this color', upload_to='products/variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productsizestock',
            unique_together={('product', 'size')},
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='productsizestock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productsizestock',
            unique_together={('product', 'size'), ('variant', 'size')},
        ),
    ]
