# Generated by Django 6.0 on 2026-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='[DEPRECATED] Use Variant images instead.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary image for this color (Optional if gallery images exist)', null=True, upload_to='products/variants/'),
        ),
    ]
