# Generated by Django 6.0 on 2026-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image_alter_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price during sale', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
